// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvI7ARmhClr_FPdN5vSNFoHD8v1x83iJs',
    appId: '1:25621826116:web:cdfb94a8be684e24a0ca11',
    messagingSenderId: '25621826116',
    projectId: 'bios-56a64',
    authDomain: 'bios-56a64.firebaseapp.com',
    storageBucket: 'bios-56a64.appspot.com',
    measurementId: 'G-S8HXXMT7XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuAkshzUd862M55YHkexEZ4BWshatgD8o',
    appId: '1:25621826116:android:e4cf86223743d14ea0ca11',
    messagingSenderId: '25621826116',
    projectId: 'bios-56a64',
    storageBucket: 'bios-56a64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Q7ZttDcMHltEki1ChYV4-0uGFC21DUg',
    appId: '1:25621826116:ios:b9a1c7f3a3f05030a0ca11',
    messagingSenderId: '25621826116',
    projectId: 'bios-56a64',
    storageBucket: 'bios-56a64.appspot.com',
    iosClientId: '25621826116-5jrooti5irnmmod6nph8p2ffnftg9omr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Q7ZttDcMHltEki1ChYV4-0uGFC21DUg',
    appId: '1:25621826116:ios:b9a1c7f3a3f05030a0ca11',
    messagingSenderId: '25621826116',
    projectId: 'bios-56a64',
    storageBucket: 'bios-56a64.appspot.com',
    iosClientId: '25621826116-5jrooti5irnmmod6nph8p2ffnftg9omr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bio',
  );
}
